version: "2.2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  logstash:
    build: logstash
    depends_on:
      - elasticsearch
    volumes:            
      - ./logstash/conf/:/data/conf      
      - ./logs/:/data/logs   
